
#server
server:
  port: 8080
#spring
spring:
 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    password: q51328401
    username: root
  messages:
     basename: messages
     encoding: UTF-8
  jackson: 
     default-property-inclusion: non_null
     
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
logging:
  level:
    com.example.demo.dao : debug