package com.example.demo.entity;

public class Studentmark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmark.Subject
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmark.s_id
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    private Integer s_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentmark.Mark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    private Integer mark;
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmark.Subject
     *
     * @return the value of studentmark.Subject
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmark.Subject
     *
     * @param subject the value for studentmark.Subject
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmark.s_id
     *
     * @return the value of studentmark.s_id
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    public Integer getS_id() {
        return s_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmark.s_id
     *
     * @param s_id the value for studentmark.s_id
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    public void setS_id(Integer s_id) {
        this.s_id = s_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentmark.Mark
     *
     * @return the value of studentmark.Mark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    public Integer getMark() {
        return mark;
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentmark.Mark
     *
     * @param mark the value for studentmark.Mark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    public void setMark(Integer mark) {
        this.mark = mark;
        
    }
    
//  //  public String toString() {
//  //     	return  " 学科:" + subject + ",分数:" +mark;
//    		
//   // 	}
}