package com.example.demo.dao;

import com.example.demo.entity.Studentinfo;
import com.example.demo.entity.StudentinfoExample;


import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface StudentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    int countByExample(StudentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    int deleteByExample(StudentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    int insert(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    int insertSelective(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    List<Studentinfo> selectByExample(StudentinfoExample example);
    
    List<Studentinfo> selectBygrade(String grade);
    
    List<Studentinfo> selectBysubject(String subject,String grade);
    List<Studentinfo> selectMarkByID(Integer ID);
    
   List<Studentinfo> selectMarkByID1(Integer ID,String subject);
  
   // public int indexOf(Object o);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") Studentinfo record, @Param("example") StudentinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated Sun Feb 21 21:57:23 CST 2021
     */
    int updateByExample(@Param("record") Studentinfo record, @Param("example") StudentinfoExample example);

	
}