package com.example.demo.dao;

import com.example.demo.entity.Studentmark;
import com.example.demo.entity.StudentmarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    int countByExample(StudentmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    int deleteByExample(StudentmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    int insert(Studentmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    int insertSelective(Studentmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    List<Studentmark> selectByExample(StudentmarkExample example);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") Studentmark record, @Param("example") StudentmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentmark
     *
     * @mbggenerated Sun Feb 21 23:33:25 CST 2021
     */
    int updateByExample(@Param("record") Studentmark record, @Param("example") StudentmarkExample example);
}